version: 1
metadata:
  name: app-mealie
entries:
  - model: authentik_providers_proxy.proxyprovider
    id: mealie-provider
    identifiers:
      name: mealie
    attrs:
      mode: forward_single
      external_host: https://mealie.prod.homeserver
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]

  - model: authentik_core.application
    id: mealie-app
    identifiers:
      slug: mealie
    attrs:
      name: Mealie
      provider: !KeyOf mealie-provider
      policy_engine_mode: any

  - model: authentik_providers_proxy.proxyprovider
    id: mealie-external-provider
    identifiers:
      name: mealie-external
    attrs:
      mode: forward_single
      external_host: https://mealie-prod.pke-lab.de
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]

  - model: authentik_core.application
    id: mealie-external-app
    identifiers:
      slug: mealie-external
    attrs:
      name: Mealie (extern)
      provider: !KeyOf mealie-external-provider
      policy_engine_mode: any

  - model: authentik_policies_expression.expressionpolicy
    id: mealie-access-policy
    identifiers:
      name: mealie-access
    attrs:
      expression: |
        return (
          ak_is_group_member(request.user, name="admins")
          or ak_is_group_member(request.user, name="mealie-user")
        )

  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf mealie-app
      policy: !KeyOf mealie-access-policy
      order: 0

  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf mealie-external-app
      policy: !KeyOf mealie-access-policy
      order: 0

