---
replicaCount: 1

image:
  repository: binwiederhier/ntfy
  pullPolicy: IfNotPresent
  tag: "v2.28.0"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: traefik
  annotations: {}
  hosts:
    - host: ntfy.tech.homeserver
      paths:
        - path: /
          pathType: Prefix
    - host: ntfy-tech.pke-lab.de
      paths:
        - path: /
          pathType: Prefix
  tls: []

persistence:
  enabled: true
  storageClassName: local-path
  size: 1Gi
  accessMode: ReadWriteOnce
  mountPath: /var/lib/ntfy

config:
  base-url: "https://ntfy-tech.pke-lab.de"
  upstream-base-url: "https://ntfy.sh"
  behind-proxy: true
  cache-file: /var/lib/ntfy/cache.db
  auth-file: /var/lib/ntfy/auth.db
  auth-default-access: "read-write"

resources:
  requests:
    cpu: 10m
    memory: 48Mi
  limits:
    cpu: 200m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
