apiVersion: v1
kind: Service
metadata:
  name: {{ include "xibosignage.memcached.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "xibosignage.memcached.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 11211
      targetPort: memcached
      protocol: TCP
      name: memcached
  selector:
    {{- include "xibosignage.memcached.selectorLabels" . | nindent 4 }}
