---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: xibosignage-secrets
  namespace: xibosignage
spec:
  encryptedData:
    db-password: AgBesYdSxFGiaU76cSOjvSEb1/C95cdK+mQiAOutsPQ7B90rXt73NDsvM/3Eji2ceTjtet5Gmx1nFGN1EvlwhSF5cCsMmOczueX2j8QbPKDV//1tjn0BhOct3/V8bSNhgMe1Lu4MP38xQMOXR5qrJi6U/y9WXEZxAfpAXyWaQnyHyII7/ksgDr18LcOni0u5iQTOXrM16PboBwIVGyTNHtFhr5UMNf0YVBseP2T7QTCFB7Ghq30EkHxBp/geslRF3YYc+IUINBRUqOyfjStKJYUDeyhmqO6U14Ag2zpq8e8VNkHUdiYFj8EcRSet7vkePaUjk3KzQv3Jd3B/PeERTrJ8+yLo2kQ0cql389XbOxpPK+1iLOeNh91Sf8DyyuRCUamq+kFoZ+rCkxfVif4NRJQV/usxy0m9Zm57vhGU8FTzQSJ1r18qGBkZNEWcP0fMIb8yHbDNrqRkpxbJrIDGNeGSdui0NvulrFRQDawuh1AG02Iz+P3e9hG6hYdnew3RXQOwuZOzYqCR5PvvoyKegMjdixFBPl1/NmYFFKoONYwvGsVRLF4+m62bReWa/dyZpeXNSlq1pmaoaTkkIoKhaFpR6Ddd442qHzQ+NzipSXz5xVB5CYkpACEZ5crdlUZgw7sCu9TjL+25BlR2suQlxxR2V9AFh5x/t1f/WT6wb1jtZfREx6xXaF7qqy4jL5W2gImCfDj075HEn7zcOsr3XT92qHyYsQ==
  template:
    metadata:
      name: xibosignage-secrets
      namespace: xibosignage
    type: Opaque
