---
apiVersion: v2
name: kubeseal-webgui
description: kubeseal-webgui web UI for Sealed Secrets deployed via ArgoCD.
type: application
version: 0.1.0
appVersion: "4.10.1"
keywords:
  - kubeseal-webgui
  - sealed-secrets
  - kubernetes
home: https://github.com/Jaydee94/kubeseal-webgui
sources:
  - https://github.com/Jaydee94/kubeseal-webgui
maintainers:
  - name: home-server-admin
dependencies:
  - name: kubeseal-webgui
    repository: oci://ghcr.io/jaydee94/kubeseal-webgui/charts
    version: "6.0.14"
