# Fuer den PROD-Cluster versiegelt (scripts/reseal-for-prod.sh), nicht mit TECH-Schluessel.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-release-watcher-zammad-token
  namespace: github-release-watcher
spec:
  encryptedData:
    token: AgAoU4twIAkTTBiunyeeB0SZmZAgUgjk29TcdBNJwzv1/2vCxBuBdNx2qlMTHPimeKD7FkzVW32iy1G+91B5iWu73FClmwF3nJKyhmzv8I+mWpr/10mGCPPDfOpSwj5xvhnQkzTVxytB/Mcevv+fSNpKzVSkPjyBXbfzu+tfYm7GTmVeCI4O/dv2G5DKmneZVGgFM7wyLWPVMOhOFrb/vOM1hTRYHQT6FyFJlpK7jBL1O5T5Cnkd1pTKZz0f7syOF9xg4CJC77j+xcIJxctLkZtwk9ovGP6PQO4mIDY8ROwnAlnmQ3Ofmn1X8mU1Mbk4KBoOs7MgMC+BKUcaSl4EYakVKiR+aJKnH7n/idNRBSHcdAlyCzJTTxHR9/AwTr7D5cvYd3HiXAZpxmhfbQ4uBGTDGfvPgVvv1VEgX438pZvaKIVZoyc4O4N05tsvgvqy7b/PjrUoYhGXG3Cy7WGJ4RlQgi5WGXAX3j8NVu6nLtfz6coocOdCAUgLQJvIhyx4lD9vfnt08bvN7ZMrh3sf8KqlTLLmuQ4RtWYi+n7J4EpYU+DUGeRxtzQssr2puvkZc2zL/4/lDB1PhjZbqvwNbkB4n8bWeX11DmtT1mdhJjtpDJr0Dr8z0RiYSWNKBOR9gsiiRrwyDXRz6coMDkNIr9J48sKXOB75DL0bQ3dAS0BIPFd/tQcTVpvYevxItmmpbge9sQIk4A+wJ3LNZ9e4cvY98Po6fShLqasT3hhGtl/sDs6Lf/f5s4boKcb91oTd+5y0ByRljeCbJRHNhTM5X5Tq
  template:
    metadata:
      name: github-release-watcher-zammad-token
      namespace: github-release-watcher
    type: Opaque
