---

secrets:
  enabled: true
  name: immich-secrets
  encryptedDbPassword: "AgBRQs+8k7zOs52gwcId4A5pyPYPXp4Sxm9Jj8UWBrFk27yXpxwyLB7RW/7lpDBgEKxhjx3DchCgZkAzONLkVHjNwcboNBVrY8Aj4mDvnbrLXx6K944T87LM+y0PINbeiTGk8wLHZgI4/fk95Z1vzeEhyBYUwSC1UkwIOw+mBQEBB/ZAuHq54rOanGkLYOolROBkQCtme9f0VDTbWoIJGH8l8dqONxUDvYfYrJzD8eB9wqjN4jLxYEeXamekgHjdGyOBySQS3PVv5rpQlNf8YNW/NeFzBBHsyKlBWgMR0dxxv0S+VsDhCged5Y7xETRijFLbdCF1p/t3EsxQ1NzjxRJNdc3+x613kTjZp/2BMWCgPg+PRA1N/YNn4GGwU8FXSm6xM08EB1mUJ6I4ADBlP1w1hLMJspW5giIFuuVzXWki/PEsy4xRLXSr8t0yvtOnLjOzZq9/T41+0wVXdn17OwrAAtdCvnnsqZQ1hatX7ELY1iC0KNal7NVAWQcYS52m08CMEOGHubMZ7CXiIW7iwIdrJqzWSO1U7ATcVdUgw/ucblyzbSeaDKVryqFkaMJ9ckWp1By/kKwI+KycrewV0eeMl402Z0BfL2evC+iL+BdKIiSAOd2qQWJnh3mlQl55JgHmG2zDryIKpZrsvCBOjlY7KYnEpQqLg8dYi+ezcNVfljG8naIDilde9cyUxE0lg0p0uiGbET8+iIBLUZmY9UdK2lfUEsnWwGpsBSlyzI+xfg=="

server:
  replicaCount: 1

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 75

  image:
    repository: ghcr.io/immich-app/immich-server
    pullPolicy: IfNotPresent
    tag: "v3.2.2"

  podSecurityContext: {}
  securityContext:
    allowPrivilegeEscalation: false

  service:
    type: ClusterIP
    port: 80
    targetPort: 2283

  ingress:
    enabled: true
    className: traefik
    annotations: {}
    hosts:
      - host: immich.prod.homeserver
        paths:
          - path: /
            pathType: Prefix
      - host: immich-prod.pke-lab.de
        paths:
          - path: /
            pathType: Prefix
    tls: []

  persistence:
    library:
      enabled: true
      storageClassName: immich-nas
      size: 500Gi
      accessMode: ReadWriteOnce

  externalLibrary:
    enabled: false
    mountPath: /mnt/external
    nfs:
      server: "192.168.178.97"
      path: "/volume2/immich-storage/external"
      readOnly: true
    extraMounts: []

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 4000m
      memory: 4Gi

  nodeSelector: {}
  tolerations: []

machineLearning:
  replicaCount: 1

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 75
    targetMemoryUtilizationPercentage: 80

  image:
    repository: ghcr.io/immich-app/immich-machine-learning
    pullPolicy: IfNotPresent
    tag: "v3.2.2"

  podSecurityContext: {}
  securityContext:
    allowPrivilegeEscalation: false

  service:
    port: 3003

  persistence:
    modelCache:
      enabled: true
      storageClassName: immich-nas
      size: 10Gi
      accessMode: ReadWriteOnce

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 4000m
      memory: 4Gi

  nodeSelector: {}
  tolerations: []

postgresql:
  replicaCount: 1
  image:
    repository: ghcr.io/immich-app/postgres
    pullPolicy: IfNotPresent
    tag: "16-vectorchord0.4.3-pgvectors0.2.1"

  database: immich
  username: immich

  service:
    port: 5432

  persistence:
    enabled: true
    storageClassName: immich-nas
    size: 20Gi
    accessMode: ReadWriteOnce

  initdbArgs: "--data-checksums"

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 2Gi

  affinity: {}

backup:
  enabled: true
  schedule: "50 1 * * *"
  timezone: "Europe/Berlin"
  suspend: false
  storageClassName: immich-nas
  size: 5Gi
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 512Mi

redis:
  image:
    repository: docker.io/valkey/valkey
    pullPolicy: IfNotPresent
    tag: "9-alpine"

  service:
    port: 6379

  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 256Mi
