apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secrets.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
spec:
  encryptedData:
    jwt-secret: {{ .Values.secrets.encryptedJwtSecret | quote }}
    key-seed: {{ .Values.secrets.encryptedKeySeed | quote }}
    root-password: {{ .Values.secrets.encryptedRootPassword | quote }}
    bind-password: {{ .Values.secrets.encryptedBindPassword | quote }}
    authentik-bind-password: {{ .Values.secrets.encryptedAuthentikBindPassword | quote }}
  template:
    metadata:
      name: {{ .Values.secrets.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
