apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "immich.ml.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "immich.ml.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.machineLearning.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "immich.ml.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "immich.ml.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.machineLearning.podSecurityContext | nindent 8 }}
      {{- with .Values.machineLearning.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.machineLearning.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.machineLearning.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: immich-machine-learning
          securityContext:
            {{- toYaml .Values.machineLearning.securityContext | nindent 12 }}
          image: "{{ .Values.machineLearning.image.repository }}:{{ .Values.machineLearning.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.machineLearning.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.machineLearning.service.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.machineLearning.resources | nindent 12 }}
          volumeMounts:
            - name: model-cache
              mountPath: /cache
      volumes:
        - name: model-cache
          {{- if .Values.machineLearning.persistence.modelCache.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "immich.ml.fullname" . }}-model-cache
          {{- else }}
          emptyDir: {}
          {{- end }}
