apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediamtx.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mediamtx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.hls }}
      targetPort: hls
      protocol: TCP
      name: hls
    - port: {{ .Values.service.ports.webrtc }}
      targetPort: webrtc
      protocol: TCP
      name: webrtc
    - port: {{ .Values.service.ports.api }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "mediamtx.selectorLabels" . | nindent 4 }}
