cert-manager:
  crds:
    enabled: true
    keep: true

  replicaCount: 1

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 20m
      memory: 64Mi

  webhook:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 32Mi

  cainjector:
    resources:
      limits:
        cpu: 150m
        memory: 192Mi
      requests:
        cpu: 10m
        memory: 32Mi

  startupapicheck:
    enabled: false
