apiVersion: v1
kind: ConfigMap
metadata:
  name: datasource-victorialogs
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  victorialogs.yaml: |
    apiVersion: 1
    datasources:
      - name: VictoriaLogs
        type: victoriametrics-logs-datasource
        access: proxy
        url: http://logging-victoria-logs-single-server.logging.svc.cluster.local:9428
        isDefault: false
        jsonData:
          maxLines: 1000
