---

libvirt_host_bridge_interface: "{{ network_interface }}"
libvirt_host_static_ip: "{{ network_static_ip }}"
disable_eee_interface: "{{ libvirt_host_bridge_interface }}"
libvirt_host_vms:
  - name: prod-vm
    vcpus: 6
    memory_mb: 24576
    disk_gb: 100
    ip: "192.168.178.99"
    prefix_length: "{{ network_prefix_length }}"
    gateway: "{{ network_gateway }}"
    dns:
      - "{{ network_static_ip }}"
    mac: "52:54:00:00:00:99"

argocd_ingress_enabled: true
argocd_ui_host: argocd.tech.homeserver
