package main

import (
	"encoding/json"
	"log/slog"
	"net/http"
	"regexp"
	"sort"
	"strings"
	"sync"
	"time"
)

const (
	// leaderboardPageSize mirrors the old db-handler.php's LIMIT 10.
	leaderboardPageSize = 10
	// maxLeaderboardEntries bounds memory use — only the top scores can
	// ever be served anyway, so nothing beyond this is worth keeping.
	maxLeaderboardEntries = 100
)

// maxPointsPerLevel mirrors validateScoreWithLevel() in pacman-canvas.js
// (104 pills + 4 powerpills + 4 ghosts per fright cycle, times 4 ghosts) —
// kept in sync manually, both sides are the same anti-cheat bound applied
// independently (client for UX, server because the client can't be trusted).
const maxPointsPerLevel = 104*10 + 4*50 + 4*4*100

// nicknamePattern matches the "<NAME>-<HEX4>" tags generated by
// nickname.js (see src/nickname.js's generateNickname()) — rejects
// anything else so the public leaderboard can't be used to store arbitrary
// strings (the real name typed into the nickname overlay never reaches
// this endpoint at all, only the derived tag).
var nicknamePattern = regexp.MustCompile(`^[A-Z0-9]{1,16}-[0-9A-F]{4}$`)

type leaderboardEntry struct {
	Nickname string    `json:"nickname"`
	Score    int       `json:"score"`
	Level    int       `json:"level"`
	Date     time.Time `json:"date"`
}

// leaderboardStore is in-memory only — no PVC is mounted (see
// values.yaml/README, readOnlyRootFilesystem: true) and pacman-server can
// run 1-3 replicas behind a plain ClusterIP Service with no session
// affinity (see autoscaling.enabled), so entries are per-pod: a
// submission can land on a different pod than a later listing, and a
// scale-down or restart drops everything. Acceptable for this training/
// demo game — documented in README.md rather than solved with shared
// storage.
type leaderboardStore struct {
	mu      sync.Mutex
	entries []leaderboardEntry
}

func newLeaderboardStore() *leaderboardStore {
	return &leaderboardStore{}
}

func (s *leaderboardStore) add(e leaderboardEntry) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.entries = append(s.entries, e)
	sort.Slice(s.entries, func(i, j int) bool { return s.entries[i].Score > s.entries[j].Score })
	if len(s.entries) > maxLeaderboardEntries {
		s.entries = s.entries[:maxLeaderboardEntries]
	}
}

func (s *leaderboardStore) top(n int) []leaderboardEntry {
	s.mu.Lock()
	defer s.mu.Unlock()
	if n > len(s.entries) {
		n = len(s.entries)
	}
	out := make([]leaderboardEntry, n)
	copy(out, s.entries[:n])
	return out
}

type leaderboardSubmission struct {
	Nickname string `json:"nickname"`
	Score    int    `json:"score"`
	Level    int    `json:"level"`
}

// handleLeaderboard serves the public leaderboard behind /api/leaderboard:
// GET returns the current top entries, POST submits one run. Replaces the
// vendored game's original data/db-handler.php (PHP, never served by this
// Go-only setup — see README.md's former "Bekannte Einschränkung").
func handleLeaderboard(logger *slog.Logger, store *leaderboardStore) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		switch r.Method {
		case http.MethodGet:
			w.Header().Set("Content-Type", "application/json")
			_ = json.NewEncoder(w).Encode(store.top(leaderboardPageSize))

		case http.MethodPost:
			r.Body = http.MaxBytesReader(w, r.Body, 1024)
			var sub leaderboardSubmission
			if err := json.NewDecoder(r.Body).Decode(&sub); err != nil {
				w.WriteHeader(http.StatusBadRequest)
				return
			}
			nickname := strings.ToUpper(strings.TrimSpace(sub.Nickname))
			if !nicknamePattern.MatchString(nickname) {
				w.WriteHeader(http.StatusBadRequest)
				return
			}
			if sub.Level < 1 || sub.Level > 10 || sub.Score < 0 || sub.Score > sub.Level*maxPointsPerLevel {
				logger.Warn("leaderboard: rejected implausible score", "nickname", nickname, "score", sub.Score, "level", sub.Level)
				w.WriteHeader(http.StatusUnprocessableEntity)
				return
			}
			store.add(leaderboardEntry{Nickname: nickname, Score: sub.Score, Level: sub.Level, Date: time.Now().UTC()})
			w.WriteHeader(http.StatusNoContent)

		default:
			w.WriteHeader(http.StatusMethodNotAllowed)
		}
	}
}
