{{- if and .Values.oidcSecret.enabled (ne .Values.oidcSecret.encryptedClientId "") -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.oidcSecret.name }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    OIDC_CLIENT_ID: {{ .Values.oidcSecret.encryptedClientId | quote }}
    OIDC_CLIENT_SECRET: {{ .Values.oidcSecret.encryptedClientSecret | quote }}
  template:
    metadata:
      name: {{ .Values.oidcSecret.name }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
