---
apiVersion: v1
kind: Secret
metadata:
  name: headlamp-admin-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Release.Name }}
type: kubernetes.io/service-account-token
