{{- if .Values.ghcrSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.ghcrSecret.name }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    ".dockerconfigjson": {{ .Values.ghcrSecret.encryptedDockerConfigJson | quote }}
  template:
    metadata:
      name: {{ .Values.ghcrSecret.name }}
      namespace: {{ .Release.Namespace }}
    type: kubernetes.io/dockerconfigjson
{{- end }}
