---
apiVersion: v2
name: glance
description: Self-hosted, schnelles Dashboard mit Übersicht über alle Home-Server-Dienste.
type: application
version: 0.1.0
appVersion: "v0.8.5"
keywords:
  - dashboard
  - homepage
  - glance
home: https://github.com/glanceapp/glance
sources:
  - https://github.com/glanceapp/glance
maintainers:
  - name: home-server-admin
