{{- if .Values.ingressPublic.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "uptime-kuma.fullname" . }}-public
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingressPublic.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "uptime-kuma.fullname" . }}
                port:
                  name: http
{{- end }}
