---

all:
  children:
    homeservers:
      hosts:
        homeserver:
          ansible_host: 192.168.178.94
          ansible_user: ubuntu
    k3s_agents:
      hosts:
        worker-0:
          ansible_host: 192.168.178.95
          ansible_user: ubuntu
        worker-1:
          ansible_host: 192.168.178.96
          ansible_user: ubuntu
    entw:
      hosts:
        entw-vm:
          ansible_host: 192.168.178.100
          ansible_user: ubuntu
    prod:
      hosts:
        prod-vm:
          ansible_host: 192.168.178.99
          ansible_user: ubuntu
    ugreen_nas:
      hosts:
        ugreen-nas:
          ansible_host: 192.168.178.97
    semaphore_targets:
      hosts:
        homeserver:
        worker-0:
        worker-1:
        vereinsheim-alarmmonitor:
        infotafel:

    raspberry_pis:
      hosts: {}

    xibo_displays:
      hosts:
        infotafel:
          ansible_host: 192.168.178.98
          ansible_user: pela
          xibo_kiosk_user: pela

    banana_pis:
      hosts:
        vereinsheim-alarmmonitor:
          ansible_host: 100.123.214.4
          ansible_user: pela
          banana_pi_kiosk_user: pela
          banana_pi_kiosk_station: 1002011_Fahrzeughalle
