---

replicaCount: 2

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

image:
  repository: cloudflare/cloudflared
  pullPolicy: IfNotPresent
  tag: "2026.8.3"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 65532

securityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 250m
    memory: 128Mi

tunnel:
  name: homeserver-prod

  id: "3faaf987-cda6-40f1-8bfe-7901b341f43e"

  credentialsSecretName: cloudflared-credentials
  encryptedCredentialsJson: "AgCoxusvPvLZVK5mG0f3wrs4eZS7VmUJA6jAF4BMnx5BD/jaVxUiybjFm4qFHI8CyqUJvqblZXls0uZNpN0P9u4AvWLFKo5nqCIpxpBuacpMZrAnhw3Ih+5st/yMC1Fd4Hb3rxF1OcJ2j5ndgR2S1RZ4rg7ySFgWRkzTB3cojameauBJmd7a+RV1myCVMvlDA5KY/c4XU7CkHXWBp7lgFpfleNkCbZtBo8nSs+aEnhhns1W8+eiSLV/wSI2SRP8mlj4ORIkV6alIAU478lBmuYCCAHPcpb+feqF1v6/V7c8k5HH+agbyJxUoaL/1Yraaa/volPRiNllEtFNrz/5Ky1+wWeqetTMpM0TuJ2ijCKCUKuO1iiYPGAA8anuEVCFNKFjDLqgQF7BqutjuWHV8r24/YhUtBYDdygMlWWsWqEfcvhEgJbToJPUiY0ZUvoil/2ejw3ZJsLJS+7SuDEsndS62m2p9b2XOtCNvhf7iuGlyTKIn1S1+6MZ8zPqg+e/vbcYSAjexiciWo0JwDcd2ExqVzALPLAT4kxCr42qpzSTegRWJA2rIXwv28PtTTuC60n/8D/DlpBd+9eMe9CMp0/lzuUuqZF7RUTy9jRDccI2jwgMMU1J7jSEkST/FK0cYubDnhv9zgYxiyTIFLYtOmu0Qu3WpXCg1ck/POFW4V67PWR7NagnvYREWDnV0iPZ7c3l+I7UtUdoi3ZUJjOWQ3ieVEYD5Tu73DUr3vg0eU2IuCadBUlg+8YRwYCVGv1TJh0RZVJIEwtN3gfSnVx3pxDg6LkjEXflJwvulUJX04Jnxv3fM+/4ep2GLXUY9zzApxoQIiATmcMnODeSuPATqE6W7UhiIbXIoRuh/ZXizyWxHoayAEV0zfs6SkwTt50EMksTSAgnrjyMyShK1ctRgNg2xj5cLXMjFcYvUo+uqZjT3"

  ingress:
    rules:
      - hostname: "*.pke-lab.de"
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true
    defaultService: "http_status:404"

nodeSelector: {}

tolerations: []

affinity: {}
