---
headlamp:
  replicaCount: null

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations: {}
    hosts:
      - host: headlamp.tech.homeserver
        paths:
          - path: /
            type: Prefix
    tls: []

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

  serviceAccount:
    create: true
