---
kubeseal-webgui:
  replicaCount: null

  image:
    pullPolicy: Always

  api:
    url: "http://kubeseal-webgui.tech.homeserver"

  sealedSecrets:
    autoFetchCert: true
    controllerName: sealed-secrets-controller
    controllerNamespace: sealed-secrets

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations: {}
    hostname: "kubeseal-webgui.tech.homeserver"
    tls:
      enabled: false
      secretName: ""

  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 20m
      memory: 256Mi

  serviceAccount:
    create: true
