apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.credentials.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
spec:
  encryptedData:
    secret-key: {{ .Values.credentials.encryptedSecretKey | quote }}
    db-password: {{ .Values.credentials.encryptedDbPassword | quote }}
    bootstrap-password: {{ .Values.credentials.encryptedBootstrapPassword | quote }}
    bootstrap-email: {{ .Values.credentials.encryptedBootstrapEmail | quote }}
    ldap-bind-password: {{ .Values.credentials.encryptedLdapBindPassword | quote }}
  template:
    metadata:
      name: {{ .Values.credentials.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
