apiVersion: v1
kind: Service
metadata:
  name: {{ include "authentik.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.server.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "authentik.serverSelectorLabels" . | nindent 4 }}
