apiVersion: v1
kind: ConfigMap
metadata:
  name: vmsingle-relabel
  namespace: {{ .Release.Namespace }}
data:
  relabel.yml: |
    - if: '{instance="vereinsheim-alarmmonitor",host=""}'
      target_label: host
      replacement: vereinsheim-alarmmonitor
    - if: '{instance="vereinsheim-alarmmonitor",kind=""}'
      target_label: kind
      replacement: pi
