apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: thermal-temperature
  namespace: {{ .Release.Namespace }}
spec:
  groups:
    - name: thermal.temperature
      interval: 30s
      rules:
        - alert: HostHighTemperature
          expr: node_hwmon_temp_celsius >= 80
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Hohe Temperatur auf {{ "{{ $labels.instance }}" }}"
            description: >-
              {{ "{{ $labels.chip }}" }}/{{ "{{ $labels.sensor }}" }} auf {{ "{{ $labels.instance }}" }}
              hat {{ "{{ $value }}" }}°C erreicht (Schwelle: 80°C).
