apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: ugreen-nas-node-exporter
  namespace: {{ .Release.Namespace }}
spec:
  jobName: ugreen-nas-node-exporter
  targetEndpoints:
    - targets:
        - "192.168.178.97:9100"
      labels:
        job: node-exporter
        instance: ugreen-nas
        host: ugreen-nas
        kind: nas
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: ugreen-nas-smartctl-exporter
  namespace: {{ .Release.Namespace }}
spec:
  jobName: ugreen-nas-smartctl-exporter
  targetEndpoints:
    - targets:
        - "192.168.178.97:9633"
      labels:
        job: smartctl-exporter
        instance: ugreen-nas
        host: ugreen-nas
        kind: nas
