apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: homeserver-smartctl-exporter
  namespace: {{ .Release.Namespace }}
spec:
  jobName: homeserver-smartctl-exporter
  targetEndpoints:
    - targets:
        - "192.168.178.94:9633"
      labels:
        job: smartctl-exporter
        instance: homeserver
        host: homeserver
        kind: server
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: worker-1-smartctl-exporter
  namespace: {{ .Release.Namespace }}
spec:
  jobName: worker-1-smartctl-exporter
  targetEndpoints:
    - targets:
        - "192.168.178.96:9633"
      labels:
        job: smartctl-exporter
        instance: worker-1
        host: worker-1
        kind: server
