---
replicaCount: 0

image:
  repository: ollama/ollama
  pullPolicy: IfNotPresent
  tag: "0.33.3"

nameOverride: ""
fullnameOverride: ""

n8nNamespace: n8n
n8nServiceAccountName: n8n

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 11434
  targetPort: 11434

persistence:
  enabled: true
  storageClassName: nas
  size: 20Gi
  accessMode: ReadWriteOnce
  mountPath: /root/.ollama

resources:
  requests:
    cpu: "3"
    memory: 6Gi
  limits:
    cpu: "4"
    memory: 7Gi

nodeSelector:
  kubernetes.io/hostname: worker-0

affinity: {}
tolerations: []
