apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homeserver-wildcard-tls
  namespace: kube-system
spec:
  secretName: homeserver-wildcard-tls
  issuerRef:
    name: homeserver-ca-issuer
    kind: ClusterIssuer
  commonName: prod.homeserver
  duration: 2160h
  renewBefore: 720h
  privateKey:
    algorithm: RSA
    size: 2048
  dnsNames:
    - alamos-apager.prod.homeserver
    - alamos-relay.prod.homeserver
    - carplay-api.prod.homeserver
    - demo.prod.homeserver
    - immich.prod.homeserver
    - mealie-native.prod.homeserver
    - mealie.prod.homeserver
    - n8n.prod.homeserver
    - nextcloud.prod.homeserver
    - pacman.prod.homeserver
    - paperless.prod.homeserver
    - stream.prod.homeserver
    - tinyteller.prod.homeserver
    - uptime-kuma-native.prod.homeserver
    - uptime-kuma.prod.homeserver
    - whoami.prod.homeserver
    - wiki.prod.homeserver
    - xibo.prod.homeserver
