---

replicaCount: 1

backend:
  image:
    repository: ghcr.io/jaydee94/tiny-teller-backend
    pullPolicy: IfNotPresent
    tag: "edge"
  port: 8080
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

frontend:
  image:
    repository: ghcr.io/jaydee94/tiny-teller-frontend
    pullPolicy: IfNotPresent
    tag: "edge"
  port: 80
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP

ingress:
  enabled: true
  className: traefik
  annotations: {}
  hosts:
    - host: tinyteller.prod.homeserver
      paths:
        - path: /
          pathType: Prefix
  tls: []

env:
  corsOrigin: "https://tinyteller.prod.homeserver"

nodeSelector: {}
tolerations: []
affinity: {}
