apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: immich-nas
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: k8s-sigs.io/immich-storage-provisioner
parameters:
  archiveOnDelete: "false"
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: false
