{{- if .Values.adminSecret.enabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.adminSecret.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gotify.labels" . | nindent 4 }}
spec:
  encryptedData:
    password: {{ .Values.adminSecret.encryptedPassword | quote }}
  template:
    metadata:
      name: {{ .Values.adminSecret.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
