apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "isc-news-bot.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.secrets.encryptedData }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  template:
    metadata:
      name: {{ .Values.secrets.name }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
