{{- if and .Values.ssoSecret.enabled (ne .Values.ssoSecret.encryptedClientId "") -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.ssoSecret.name }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    clientId: {{ .Values.ssoSecret.encryptedClientId | quote }}
    clientSecret: {{ .Values.ssoSecret.encryptedClientSecret | quote }}
  template:
    metadata:
      name: {{ .Values.ssoSecret.name }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
