fullnameOverride: "pacman"

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

image:
  repository: ghcr.io/pkr-lab/pacman
  tag: "v8"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: traefik
  annotations: {}
  hosts:
    - host: pacman.prod.homeserver
      paths:
        - path: /
          pathType: Prefix
    - host: pacman-prod.pke-lab.de
      paths:
        - path: /
          pathType: Prefix
  tls: []

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    cpu: 100m
    memory: 64Mi

geoip:
  enabled: true
  updaterImage:
    repository: curlimages/curl
    tag: "8.22.0"

trainingMode:
  enabled: true
