apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.rootCreds.name }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    rootUser: {{ .Values.rootCreds.encryptedRootUser | quote }}
    rootPassword: {{ .Values.rootCreds.encryptedRootPassword | quote }}
  template:
    metadata:
      name: {{ .Values.rootCreds.name }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
