# Fuer den PROD-Cluster versiegelt (scripts/reseal-for-prod.sh), nicht mit TECH-Schluessel.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-secrets
  namespace: immich
spec:
  encryptedData:
    db-password: AgAadQh03dTpSOwVGAunmKe51ccfWmmaBHT988863ot1r4g2ol6/dWtGlOhA65R22zTryebqXzUUSiNX/RoBFmwSmcG7WFpP0i/7k6M3ZKo5j5tLY3+uyXsCUTDYednys/FOHY6mm2kvleqRk5jKp4ytr9+GxJXQP14denrsxipQcDpz6FLl4P35P3RnaNmxPTNaIM6Vn/hhdFtXcx54TY5N1ebXAlMafqt5mpf10ZmZdSLMKFlepT3gDq/+Ue+rJAYl/zNp0aunagTi2zR3rox9v7orIOtnZV93W+m8JiTXj8hSBOGTPWRIlqf842mRH88vSwS7PtYSJ/UvEN/TCUyObf+yKt1vi6HiibDkCx75s8mutl5GaDt+SOsNUUFoH5Sw1SB9OwRGIf7jlW0iYjq9QfErPaffhjlN69RqDEusCY0/tTEpnFut0p1qjHninn5heCWdjpqu5BQbr7A98NIMtgvMoZBk0NJKn9e/al0gkAzAyrT3Yjiqfbbz4OL3KVX/S+kySExa8ZXTbmitoaiXMGB2DvlIkGK+QY8gtnL3RyiVmjPkMOr/bRB9TT32DyXYrPL1oGmt/+yU+kcOnrlMWtALnoQsfluckHuV/eJsf1toufmvQh0TBfQ9WlWiEMu+IeDLhBb6kBVnnpaHhUXd7ou2OYrQYoMf2rs5Q7LAO8s/ezlFB4bmvdJffE5bVK3xgCXr6dQYDSKAb0kdmLN8CXaVQ/C8/HjysoXdbkOw6A==
  template:
    metadata:
      name: immich-secrets
      namespace: immich
    type: Opaque
