apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextcloud.postgresql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextcloud.postgresql.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "nextcloud.postgresql.selectorLabels" . | nindent 4 }}
