---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wikijs-secrets
  namespace: wikijs
spec:
  encryptedData:
    db-password: AgC2+P8/iUMjZGiiy/ZY4nBbiVR9O9NITvVcVwnOvoCFfxCYT11TKGYeukLRb6Fq1TnSL/wU2xmWTClLXIgbCRJanaQH+7bvJHF3AzZDhlb9gB8BCXCc1wrQqa4m2soxuggjJBdP9w1wz9/FgiGb+znXIT7enDZ/LBaPDA3IhXbN9MSr3gUXCen5XynfOr+RXVTgN1rEkvOek64sHW9KSryxZxHXm3YHH2w+jMKIiFj2RFEn15FnsBfGAv6csf3R7A38PjpPHd35BN38PSHUIWGcHptQrivjXvbp4XT28DOAml+mDq/ofFXsaMWc/ubiBvkH6boUBqLWmxG3UEm3Mr+0MAZ/jf1xUz0N7nanh4uVqJGv0f/JSl10U5+1A9I2vj60We1yinTUHQxfE2ELkR4JYoJ06kcP4HcrOmROJSiBqBKNjn88jw+U2WYGyRTqCLDPG3Y2ViFt96n6rbo2UAo7gm+D165Gmlw5hTzCQyYWAZWHURxsI3AJppfwAT8Hss3aKdTixMt6CkDHHonviG4nBhmWr7N7JKlq3XAhkNvO7U7w/PiydxN/a422tEZZedP55OWtX0n9+he+PrKD1K6ck88eQVdwaDVvjud5dFrGUSm0j3JeqCXm4h6yizoej3IPJHXrPP1iUSL95Or68Mbovzohi4JcgHlsal6Gf8HYycBjo5JVuTTBHn00mgr9pNxuxG+WMfyAvsgybO3N/SP9vDIie+2mFj0EOqqfcAqTng==
  template:
    metadata:
      name: wikijs-secrets
      namespace: wikijs
    type: Opaque
