---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wiki-docs-sync-wikijs-token
  namespace: wiki-docs-sync
spec:
  encryptedData:
    token: AgCAS6EIi+vzQXT83AinQFMoW6aWrcMCP3LBKJJ3X8kPtatOWFXxY9u4MsGC7tJNEPootgmz2KE3UXF3minQZgvQmpFwMkK6wOtEKubzBlw8DJegVjomBK6JS0chrQ6clE1BgbluVmZ9zYoiUKSM8hjHoVm0/iK3HO8s51K71hEHMFZS2oW+amk15XNjJDpjzshUsoGTKJFRuEjps+QvFyS/XTvosOdgs/LMoJWLv63eyTfcW2PudcWJ6Xb25qG4ap/2iU8VfYsZDZoyaHz+yMKlzKtF/4oFsnGr+UvN7FdJ6kpU5MimpnbHeQPJSNHxdMjCz38Og5rw3HJibve4WXrd0PnXFSna1EKuJsoRDr+TXj2aHn+9WQulzRFkE6T1Kmf9tFUdL4C8chn1qIVSzms8MI6pYAw691my6UGAduBoUQrW19icqNSXlOsu7hhkNabSJtm0tDLki/jS/9PHylwpFJxdOZigQ2N5KGxrjNSLLYLQT5e8/sPrMXFLG3RDiTT0yy4JHIb4i4/1/nBxaBx+yLbhsQS4JFEzLu75xZG+1UbS9u/b2f5u3caeTLTdyI31+eZx6lA11gclpIgEuaEzsieXMRB+swQg4+5Zl/iGoRY2481m4NX+VrnDH0gntLiebIVE6cazV98zOxmBlINO7ECGmWiJfedm7dULERDBJhvQSwV10PmXiphYsdcYDLkAt+cU5lj1/Ijgzck9x3diYK7JEpI+G6jRlhDicHX9RlBhLcOYo0uKKWrV1o6VxZbdOFICcp1y7mxWxRq+ihid9T6S/cyZY1mPsatpbygaRxTK7/PXmr75yRYuErNZWKv0WrD6u9SGASgVnu8lKBUQvtsSOJDc0xF2xwoKL6jHL6V/oY/HhgNCapp16JYvc27Yotx0N7K6Xk2YEyDqyoBtM/SQoy0TBmp0QPCmuxRK96gG2Qg+Eg7IjzSFisi/mzixnUoNti5J2tiRqAvlHXJ2koikTgM69mU+Znp+F9YrXKGSRhN+3aZR9/Op8LyP0a1XC5O042eIg901iHdbM+rI1862VMtoTf5Y9Etoo+r6GoRcvZdicSC9RSJJE0Hqphk4TJoeU5H5oP/odbv0ReDqPJWicecrepu6L07x5IlmMF5TD502za6Z2fp/AS91jZKNrA/9CVo/RAXeGzvzBlbHanem7kB/DypP5gMTlafhcCeVHxOe2HJ2nWM0YKJw1ZaeBxvhSagDdmZzkl4ix1h+6nPRPW6/XES4t0Av7AlxqYJkFJelEY56c5SHMwtkS7M/2IBdWW8n+d3+Y3FRT+p4Kf4MmdLwvL/Egh3TMzT4rA6OCPnZoQLwDbaTvczUEDZ4oyzmlF624ejJHzEIypiODYbpvvAQ
  template:
    metadata:
      name: wiki-docs-sync-wikijs-token
      namespace: wiki-docs-sync
    type: Opaque
