---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-api-token
  namespace: wiki-docs-sync
spec:
  encryptedData:
    token: AgBZxilvr/lNIUy/d0A+akvXeuTo0tr1W5wPq3jVBCnxAIN9TBdEYcGBo0cvObRmlGJi+pjCUa1Ouu6ssIBAxLRgBQOwMrtRA4h0dQmt3SlA6A2/z3tQaO6m0Y180bdojKA9dvrFi0UgE1OH1okNZgwWkNJMFWzl/c4Z2dtsXpR0GHS3aRYDqZA/lT97Aj4IsyQmCGCG641Vk0I0A3+4Ca3/GwnYsJ4row4lHQSrEol0jm9uyiXqGzhSutkj2eF3ty9ken3A6p0RAHeOYNgEm05RaN0/sxdFnloyA4Qk7EQLDsJtWoUnoGQmPyK/YVMfPqKUCumFFDtmMjB/ePbjYI0/jCoVuR8J3gB5WKDUopu4fXSksfI5oRosPc48mpih1Iob2kO5TH0ZIQG82Gk1jT36Kdot+FtOkZfJ/Vt0c1mccbwA7Iayzn2VcN39Whn0WoKEuHaQzPE+LmaTWOGwKpe/CQyqBxXNvoeGtWgWupELBiASvsFPRepHYXlNyayTp4lC3bsbkhWx1uoMAKlW5E5rZrGX1xREZb9AxapH5A9nC5NBSDfdeGb0NZbIgBAQER9LxLbbWKfoYJSDLokH8tv2xLZpQ4iGEmxb4EN4JlH2XxlzkK5UDyL/hkdr/751mAa1e1tRakvRfNtu7TkSqizJdBor77iUr7S29mudsiNYKjIEpFz+9E6AMeqHEcb+RSyhFnvj01rRfxmlDgzrHZ6fdtQiC5uTNsjZY8BcjhyAUzGheGdl6qIxuhrOCizaCz/MTWiZQTMFVz+rBPAtl81KsRqcN49TwHgSXWPlW4E9lC5xySAjpG2u/L3iOQo=
  template:
    metadata:
      name: github-api-token
      namespace: wiki-docs-sync
