{{- if .Values.secrets.enabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wikijs.labels" . | nindent 4 }}
spec:
  encryptedData:
    db-password: {{ .Values.secrets.encryptedDbPassword | quote }}
  template:
    metadata:
      name: {{ .Values.secrets.name }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
