---
tailscale_repo_codename: "{{ ansible_distribution_release }}"

tailscale_repo_os: "{{ 'debian' if ansible_distribution == 'Debian' else 'ubuntu' }}"

tailscale_accept_routes: false

tailscale_advertise_routes: "{{ local_subnet }}"
