{{- if .Values.secrets.tankerkoenig.enabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secrets.tankerkoenig.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "glance.labels" . | nindent 4 }}
spec:
  encryptedData:
    apikey: {{ .Values.secrets.tankerkoenig.encryptedApiKey | quote }}
  template:
    metadata:
      name: {{ .Values.secrets.tankerkoenig.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
