apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "alamos-relay.fullname" . }}-allow-egress-n8n
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "alamos-relay.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.n8nNamespace }}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: n8n
      ports:
        - protocol: TCP
          port: {{ .Values.n8nTargetPort }}
