---
hostname: entw-vm
timezone: Europe/Berlin

network_configure_static_ip: false

k3s_pod_cidr: "10.44.0.0/16"
k3s_service_cidr: "10.45.0.0/16"
k3s_server_ip: "192.168.178.100"
k3s_audit_log_enabled: false
k3s_kubelet_memory_protection_enabled: false
k3s_secrets_encryption_enabled: false

argocd_repo_revision: entw
argocd_entw_layout: true
argocd_platform_apps:
  - sealed-secrets
argocd_workloads_apps:
  - demo-app
  - example-whoami
argocd_network_policy_refined_namespaces:
  - example-whoami
  - sealed-secrets
argocd_network_policy_excluded_apps: []
argocd_network_policy_extra_ingress: {}
