{{- if .Values.secrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    token: {{ .Values.secrets.encryptedToken | quote }}
  template:
    metadata:
      name: {{ .Values.secrets.name }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
