apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.tunnel.credentialsSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
spec:
  encryptedData:
    credentials.json: {{ .Values.tunnel.encryptedCredentialsJson | quote }}
  template:
    metadata:
      name: {{ .Values.tunnel.credentialsSecretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
