{{- if .Values.adminSecret.enabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.adminSecret.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
spec:
  encryptedData:
    admin-token: {{ .Values.adminSecret.encryptedAdminToken | quote }}
  template:
    metadata:
      name: {{ .Values.adminSecret.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
{{- if .Values.smtpSecret.enabled }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.smtpSecret.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
spec:
  encryptedData:
    smtp-password: {{ .Values.smtpSecret.encryptedSmtpPassword | quote }}
  template:
    metadata:
      name: {{ .Values.smtpSecret.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
