---
banana_pi_kiosk_enabled: true

banana_pi_kiosk_base_url: "https://alamos-apager.prod.homeserver"

banana_pi_kiosk_user: "pela"

banana_pi_kiosk_heartbeat_interval: 60

banana_pi_kiosk_failover_poll_seconds: 30

banana_pi_kiosk_failover_fail_threshold: 3

banana_pi_kiosk_failover_recover_threshold: 1

banana_pi_kiosk_periodic_refresh_seconds: 0

banana_pi_kiosk_daily_reboot_enabled: false

banana_pi_kiosk_daily_reboot_time: "00:00:00"

banana_pi_kiosk_wol_enabled: true

banana_pi_kiosk_wol_devices: {}

banana_pi_kiosk_wol_agent_enabled: true
banana_pi_kiosk_wol_agent_port: 9102

banana_pi_kiosk_wol_agent_token_path: /etc/banana-pi-wol-agent/token
