apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "day-pilot.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "day-pilot.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  storageClassName: {{ .Values.postgres.persistence.storageClassName }}
  accessModes:
    - {{ .Values.postgres.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
