{{- if .Values.secrets.enabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "day-pilot.labels" . | nindent 4 }}
spec:
  encryptedData:
    postgres-password: {{ .Values.secrets.encryptedPostgresPassword | quote }}
    openai-api-key: {{ .Values.secrets.encryptedOpenaiApiKey | quote }}
    github-token: {{ .Values.secrets.encryptedGithubToken | quote }}
    weatherapi-api-key: {{ .Values.secrets.encryptedWeatherapiApiKey | quote }}
    caldav-password: {{ .Values.secrets.encryptedCaldavPassword | quote }}
    ntfy-token: {{ .Values.secrets.encryptedNtfyToken | quote }}
    voice-webhook-secret: {{ .Values.secrets.encryptedVoiceWebhookSecret | quote }}
  template:
    metadata:
      name: {{ .Values.secrets.name }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
