---
- name: Homeserver-CA-Vertrauensspeicher aktualisieren
  ansible.builtin.command: update-ca-certificates
  changed_when: true

- name: Restart banana-pi heartbeat timer
  ansible.builtin.systemd:
    name: banana-pi-heartbeat.timer
    daemon_reload: true
    state: restarted

- name: Reload getty@tty1
  ansible.builtin.systemd:
    daemon_reload: true
    name: getty@tty1.service
    state: restarted

- name: Restart banana-pi daily reboot timer
  ansible.builtin.systemd:
    name: banana-pi-daily-reboot.timer
    daemon_reload: true
    state: restarted

- name: Restart banana-pi wol agent
  ansible.builtin.systemd:
    name: banana-pi-wol-agent
    daemon_reload: true
    state: restarted
