apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secrets.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authelia.labels" . | nindent 4 }}
spec:
  encryptedData:
    jwt-secret: {{ .Values.secrets.encryptedJwtSecret | quote }}
    session-secret: {{ .Values.secrets.encryptedSessionSecret | quote }}
    storage-encryption-key: {{ .Values.secrets.encryptedStorageEncryptionKey | quote }}
    users_database.yml: {{ .Values.secrets.encryptedUsersDatabase | quote }}
  template:
    metadata:
      name: {{ .Values.secrets.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
