---

libvirt_host_enabled: false

libvirt_host_configure_bridge: false
libvirt_host_bridge_name: br0
libvirt_host_bridge_interface: "{{ ansible_default_ipv4.interface }}"

libvirt_host_static_ip: "{{ ansible_default_ipv4.address }}"
libvirt_host_gateway: "{{ ansible_default_ipv4.gateway }}"
libvirt_host_prefix_length: "{{ network_prefix_length | default(24) }}"
libvirt_host_dns: "{{ network_dns | default(['1.1.1.1', '8.8.8.8']) }}"

libvirt_host_pool_dir: /var/lib/libvirt/images

libvirt_host_base_image_url: "https://cloud-images.ubuntu.com/releases/resolute/release/ubuntu-26.04-server-cloudimg-amd64.img"
libvirt_host_base_image_name: "ubuntu-26.04-server-cloudimg-amd64.img"

libvirt_host_guests_on_boot: start
libvirt_host_guests_on_shutdown: shutdown
libvirt_host_guests_shutdown_timeout: 300

libvirt_host_admin_ssh_public_key: ""

libvirt_host_vms: []
