---
vmagent_enabled: true

vmagent_version: "1.149.0"

vmagent_arch: "arm"

vmagent_download_url: >-
  https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v{{ vmagent_version }}/vmutils-linux-{{ vmagent_arch }}-v{{ vmagent_version }}.tar.gz

vmagent_install_dir: "/opt/vmagent-{{ vmagent_version }}"

vmagent_node_exporter_port: 9100
vmagent_scrape_interval: "30s"

