# Mit dem TECH-Schluessel versiegelt.
# GitHub-Lese-Token (fine-grained, nur oeffentliche Repos), erzeugt mit scripts/seal-github-token.sh.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-api-token
  namespace: github-release-watcher
spec:
  encryptedData:
    token: AgCTg6HJoeVu7jZnl7Y6YRUxIFilol3v228HYHe9ZcEC7N8yvaciSRYCdu0kM+UIr+dWS3f3/sZIxyiX6TBa/LLxFfB4/QcbvRRpXZDAmbb6RApxjY9QD81ug0d07b1imNlpgVDxD0MTJfhx92ltKae+MfdPu8NcjLpwFcA96QJWh/QFSJe2QPJmmvHM+dxwDrcY5Rh57EMXj67kZmioZlGggdJ6HvxvcHtncv8vm96HERShp2d7iXgZpbVzl0VdUWly3kaZ/FvLEVv8sbYP+24Wx+2S5wBTvhlOOPuR8ePOM0nUiGURVM2nKrFAKzpXkEzj6ZBB0mxWTJLCtOd8XhNHq6gTVIcRu+6LcKSPwsC/kKo9hEq2IpB77Iqw+L5O9EfC2CGHHJdkjKTQYdKS2lB4P50nW0rjzF8i10aMM4ngg3n+4lY67tiQZglgNmoEkbIxpm2VdSRYp8oRlCQSm9Mys1dc8gf2+3xHJeuhRCITRLsFp668pdIwvVUqAHkNH4BNUyMA8zwWZfdJd9HnSHwdGqXxxDPLY796kPJPMqus16/PpXR1/iRfhtAAQBhHYOvL+nnT02u41i7mHbqyzQQttxRFiN6Jtfsc9Q9kdBJe/jvLCy30TN5duna3PtXIlE3aScT18S9eAjue4it+At6uP/pwgB2M/BngNEEOK//IAF2k6EooBKRouVDa/PkftCvHhTvoV/DAAnilvSc4OZNMBip0ZuG5YBGeK+D7xAOtZjtWPEZ/iu3dhXR/7kvK8H+gJORjlUMy6pMaVHRNuIMA4ddJj/odVzblp5noFg+hwzEj8tN10bvhWvDJ1J8=
  template:
    metadata:
      name: github-api-token
      namespace: github-release-watcher
