apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ollama.fullname" . }}-default-deny
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
