---
replicaCount: 1

image:
  repository: louislam/uptime-kuma
  pullPolicy: IfNotPresent
  tag: "2.5.5"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false

env:
  PUID: "1000"
  PGID: "1000"
  NODE_EXTRA_CA_CERTS: "/etc/ssl/homeserver-ca/homeserver-root-ca.pem"

service:
  type: ClusterIP
  port: 80
  targetPort: 3001

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "authentik-authentik@kubernetescrd"
  hosts:
    - host: uptime-kuma.prod.homeserver
      paths:
        - path: /
          pathType: Prefix
  tls: []

ingressPublic:
  enabled: true
  host: status-prod.pke-lab.de

ingressNative:
  enabled: true
  host: uptime-kuma-native.prod.homeserver

persistence:
  enabled: true
  storageClassName: local-path
  size: 2Gi
  accessMode: ReadWriteOnce
  mountPath: /app/data

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

affinity: {}

nodeSelector:
  kubernetes.io/hostname: homeserver
tolerations: []
