{{- if .Values.geoip.enabled }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.geoip.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    {{ .Values.geoip.accountIdKey }}: {{ .Values.geoip.encryptedAccountId }}
    {{ .Values.geoip.licenseKeyKey }}: {{ .Values.geoip.encryptedLicenseKey }}
  template:
    metadata:
      name: {{ .Values.geoip.secretName }}
      namespace: {{ .Release.Namespace }}
{{- end }}
