---

- name: Deploy PROD cluster (k3s) in the homeserver KVM VM
  hosts: prod-vm
  become: true
  roles:
    - role: common
      tags: [common, base]
    - role: node_exporter
      tags: [node-exporter, monitoring]
    - role: k3s
      tags: [k3s, kubernetes]
