{{- if .Values.credentials.enabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.credentials.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authentik-wrapper.labels" . | nindent 4 }}
spec:
  encryptedData:
    secret_key: {{ .Values.credentials.encryptedSecretKey | quote }}
    db_password: {{ .Values.credentials.encryptedDbPassword | quote }}
    bootstrap_password: {{ .Values.credentials.encryptedBootstrapPassword | quote }}
    bootstrap_email: {{ .Values.credentials.encryptedBootstrapEmail | quote }}
  template:
    metadata:
      name: {{ .Values.credentials.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
