{{- if and .Values.tls.enabled (ne .Values.tls.encryptedCrt "") -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.tls.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authentik-wrapper.labels" . | nindent 4 }}
spec:
  encryptedData:
    tls.crt: {{ .Values.tls.encryptedCrt | quote }}
    tls.key: {{ .Values.tls.encryptedKey | quote }}
  template:
    metadata:
      name: {{ .Values.tls.secretName }}
      namespace: {{ .Release.Namespace }}
    type: kubernetes.io/tls
{{- end }}
