---
worker_apt_update_enabled: true

worker_apt_update_k3s_node_name: "{{ k3s_agent_hostname }}"

worker_apt_update_kubeconfig: /etc/rancher/k3s/k3s.yaml

worker_apt_update_reboot_timeout_seconds: 300
worker_apt_update_post_reboot_delay_seconds: 15

worker_apt_update_dns_fallback_enabled: false
worker_apt_update_dns_fallback_interface: "eno1"
worker_apt_update_dns_fallback_servers:
  - "1.1.1.1"
  - "8.8.8.8"
