---
xibo_kiosk_enabled: true

xibo_kiosk_nfs_server: "192.168.178.97"
xibo_kiosk_nfs_path: "/volume1/k8s-storage/xibosignage-display"
xibo_kiosk_mount_point: "/mnt/xibosignage-display"

xibo_kiosk_http_port: 8080
xibo_kiosk_web_root: "/var/www/xibosignage-slideshow"

xibo_kiosk_manifest_interval_seconds: 30

xibo_kiosk_slide_duration_ms: 10000

xibo_kiosk_user: "pi"
