{{- if .Values.secrets.powerAgentToken.enabled }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secrets.powerAgentToken.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    {{ .Values.secrets.powerAgentToken.secretKey }}: {{ .Values.secrets.powerAgentToken.encryptedData }}
  template:
    metadata:
      name: {{ .Values.secrets.powerAgentToken.secretName }}
      namespace: {{ .Release.Namespace }}
{{- end }}
