apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homeserver-wildcard-tls
  namespace: kube-system
spec:
  secretName: homeserver-wildcard-tls
  issuerRef:
    name: homeserver-ca-issuer
    kind: ClusterIssuer
  commonName: homeserver
  duration: 2160h
  renewBefore: 720h
  privateKey:
    algorithm: RSA
    size: 2048
  dnsNames:
    - homeserver
    - alamos-apager.prod.homeserver
    - alamos-relay.prod.homeserver
    - argo-workflows.tech.homeserver
    - argocd.tech.homeserver
    - authentik.tech.homeserver
    - carplay-api.prod.homeserver
    - demo.prod.homeserver
    - gotify-api.tech.homeserver
    - gotify.tech.homeserver
    - grafana.tech.homeserver
    - headlamp.tech.homeserver
    - immich.prod.homeserver
    - kubeseal-webgui.tech.homeserver
    - lldap.tech.homeserver
    - logs-write.tech.homeserver
    - mealie.prod.homeserver
    - mealie-native.prod.homeserver
    - minio.tech.homeserver
    - n8n.prod.homeserver
    - nextcloud.prod.homeserver
    - ntfy.tech.homeserver
    - pacman.prod.homeserver
    - paperless.prod.homeserver
    - pihole.tech.homeserver
    - semaphore-api.tech.homeserver
    - semaphore.tech.homeserver
    - stream.prod.homeserver
    - tinyteller.prod.homeserver
    - uptime-kuma.prod.homeserver
    - uptime-kuma-native.prod.homeserver
    - vault.tech.homeserver
    - vm-write.tech.homeserver
    - whoami.prod.homeserver
    - wiki.prod.homeserver
    - xibo.prod.homeserver
    - zammad.tech.homeserver
