---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alamos-apager-stations
  namespace: alamos-apager
spec:
  encryptedData:
    1002011_Fahrzeughalle: AgBbhTePbqcv85ihrlwKqKD3bwW7hP3j0xIDaO92pGtsTbtqdCfvrMWg1TYuedTluVxrTYuaosA/5torDJiVPEwsnKjOU3SHkkBxH3bhsXODEQD3q4qCmYhPzPWd3Qlddm18OdFBklGP9szRkL3AlQ0Frb9EwxbmoWdTYc1s5SUB5gYs4zbQVO9aiVcHzJQg72QcDEqdCDnJ5YMR6BIEUtw06xjpZuk6rkqQ+EcHzFebq2kUN2Q3rzgLsyvaWsSoGo7w6Pk+ucaz+xF/b+m0Zrr0RPhZf8TdNEVoG5sQ4xd1/w3GvJaVcts/i1S4JmlXTwCDZ9lZC4u47kzoBiL2BPuFZPKpZx79dHA36eTe9SN6YNJQkXe3aJ8NdV2YnD2hbdEZ2tnVwJ8U7RgwrHZSuTIVcPIP0heSHgKwcmiELecdEn6TS2YNNkZn6OZ7V5I9ZK6NU/2buQCWri41rQVIYpa9rODwGXJAIWYUh1uYbTEovWA9Nvz4+R5ma8QOaV4WPMFV1QlH7uZ308X4owuL0FctpL242BlYt2FyCLHx3jbI2op4zLTC0u3zrlFUr1mfO681lA3neeSqG4u1tsbytJQ0YgZ8YR1T9N6/hgWxUvsmWNu/pK8SDO/6I8o4cg6JvqnW2USuIGJGosrjLou2r5HiMbOCOYUvM+DUqaJ08CWt9hDJpKPUwo4Nl2qnYkSYLOkjkFSY6YcIJzRnnWoE5iC2nqsqY84MdPjMKlqptmBRLPczG003lWmv9E96K62/LOHxeRuGWL9t3XXY/0SD8wQp
  template:
    metadata:
      name: alamos-apager-stations
      namespace: alamos-apager
