version: 1
metadata:
  name: outpost-providers
entries:
  - model: authentik_outposts.outpost
    identifiers:
      name: authentik Embedded Outpost
    attrs:
      providers:
        - !Find [authentik_providers_proxy.proxyprovider, [name, "mealie"]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, "mealie-external"]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, "uptime-kuma"]]
    state: present
