version: 1
metadata:
  name: cleanup-renamed-policies
entries:
  - model: authentik_policies_expression.expressionpolicy
    identifiers:
      name: mealie-rdn-only
    state: absent
  - model: authentik_policies_expression.expressionpolicy
    identifiers:
      name: uptime-kuma-admins-only
    state: absent
