---

secrets:
  enabled: true
  name: xibosignage-secrets
  encryptedDbPassword: "AgBAX89mcUQAsCTHWI2TA0f5fxBq5HyL95WXuSMIknfCEwtI/LSxkKc4tCIt5X6g3zskLNNUG9IJfGfs13gaRBg3hH4ad0EdRsTrlIvohidSJUqnxcge4uUd09GWd/aBRcQOWY7e3REB2Af+Cc1IiqrXA9Ivo2FVEICKvzjD/ZWOyXZLR3kHXAZFdBHzwGSu79iMmVWF4CHNAiIdNmqFCPr4el/92I1UDnCkgCTkWbm5rO3ye7kdMqHvwvh0B74olFInFm35k2AI0pkOsQZ0oC5xfzb5nU7NC97vUxP0SMFKQ/I3sn+MJ28iwjziHgjMMPacYlYe1YuScu0Wfrx0BThTS4JagsIMFwRTahw8c+Aq8T+fGJdTpXb2ozbfO/hlLZDRugg3Ympomcp+WGu9aj0Pow8JSsWjRUA4qaji2KPH+RDwxf0lwjFs0pVsdUrZ9Q0YkvH27I6eA15Urv1P8hfM6TwnRF3LYdLs6le/AI59w0MbPmNRmY9mcmx1VTdrtRgImUb3cJ9uyEa6x9S6zc+DuXD9c6VdkJiESmGJqiGz7hcv/NonCOsndHXsnQkUJVVjHAFp47nT/xuBFtH+1uaKkH5CqFyA0fIkEQ1jAvqij8kRo6odSaW9Z1CcgLZt/8JREMveZT51P2Wzmy5uItjtw76IBf/S5b75BEajmo4XrDtmuaoFbWeZBT1mS/A3eQ4/ImCURLAqgr2M5wDPls6xgxxSpQ=="

mysql:
  replicaCount: 1
  image:
    repository: mysql
    pullPolicy: IfNotPresent
    tag: "26.7"

  database: cms
  username: cms

  service:
    port: 3306

  persistence:
    enabled: true
    storageClassName: nas
    size: 10Gi
    accessMode: ReadWriteOnce

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi

  affinity: {}

xmr:
  image:
    repository: ghcr.io/xibosignage/xibo-xmr
    pullPolicy: IfNotPresent
    tag: "1.3"

  service:
    port: 9505

  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      memory: 256Mi

memcached:
  image:
    repository: memcached
    pullPolicy: IfNotPresent
    tag: "alpine"
  args: ["-m", "15"]

  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 100Mi

quickchart:
  enabled: true
  image:
    repository: ianw/quickchart
    pullPolicy: IfNotPresent
    tag: "latest"

  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      memory: 256Mi

cms:
  replicaCount: 1

  image:
    repository: ghcr.io/xibosignage/xibo-cms
    pullPolicy: IfNotPresent
    tag: "release-4.5.0"

  service:
    type: ClusterIP
    port: 80
    targetPort: 80

  ingress:
    enabled: true
    className: traefik
    annotations: {}
    hosts:
      - host: xibo.prod.homeserver
        paths:
          - path: /
            pathType: Prefix
      - host: xibo-prod.pke-lab.de
        paths:
          - path: /
            pathType: Prefix
    tls: []

  env:
    CMS_SERVER_NAME: "xibo.prod.homeserver"
    CMS_USE_MEMCACHED: "true"
    XTR_ENABLED: "true"
    CMS_PHP_POST_MAX_SIZE: "512M"
    CMS_PHP_UPLOAD_MAX_FILESIZE: "512M"
    CMS_PHP_MAX_EXECUTION_TIME: "600"

  securityContext: {}

  persistence:
    library:
      enabled: true
      storageClassName: nas
      size: 50Gi
      accessMode: ReadWriteOnce
    state:
      enabled: true
      storageClassName: nas
      size: 2Gi
      accessMode: ReadWriteOnce

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 1Gi

  affinity: {}
  nodeSelector: {}
  tolerations: []
