---

victoria-logs-single:
  server:
    retentionPeriod: 14

    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

    persistentVolume:
      enabled: true
      storageClassName: local-path
      size: 10Gi

    nodeSelector:
      kubernetes.io/hostname: homeserver

victoria-logs-collector:
  remoteWrite:
    - url: http://logging-victoria-logs-single-server:9428

  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 128Mi
