---
replicaCount: 1

image:
  repository: louislam/uptime-kuma
  pullPolicy: IfNotPresent
  tag: "1.23.15"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 3001

ingress:
  enabled: true
  className: traefik
  annotations: {}
  hosts:
    - host: uptime-kuma.homeserver
      paths:
        - path: /
          pathType: Prefix
  tls: []

persistence:
  enabled: true
  storageClassName: nas
  size: 2Gi
  accessMode: ReadWriteOnce
  mountPath: /app/data

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

affinity: {}

nodeSelector: {}
tolerations: []
