{{- if and .Values.oidcSecret.enabled (ne .Values.oidcSecret.encryptedClientId "") -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.oidcSecret.name }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    clientId: {{ .Values.oidcSecret.encryptedClientId | quote }}
    clientSecret: {{ .Values.oidcSecret.encryptedClientSecret | quote }}
  template:
    metadata:
      name: {{ .Values.oidcSecret.name }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
